/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumPdfStatus } from "./EnumPdfStatus";
import { JsonFilter } from "../../util/JsonFilter";
import { ExtractedContentListRelationFilter } from "../../extractedContent/base/ExtractedContentListRelationFilter";

@InputType()
class PdfWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  uploadDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fileName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumPdfStatus,
  })
  @IsEnum(EnumPdfStatus)
  @IsOptional()
  @Field(() => EnumPdfStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  metadata?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => ExtractedContentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExtractedContentListRelationFilter)
  @IsOptional()
  @Field(() => ExtractedContentListRelationFilter, {
    nullable: true,
  })
  extractedContents?: ExtractedContentListRelationFilter;
}

export { PdfWhereInput as PdfWhereInput };
